/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NegotiationRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptedA"
      | "acceptedB"
      | "counterpartyEscrow"
      | "counterpartyPrice"
      | "creatorPrice"
      | "decidedA"
      | "decidedB"
      | "finalSettlement"
      | "getStatusLabel"
      | "hasDeal"
      | "partyA"
      | "partyB"
      | "proposedSettlement"
      | "respondToProposal"
      | "status"
      | "submitCounterpartyPrice"
      | "submittedB"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CounterpartyPriceSubmitted"
      | "DecisionSubmitted"
      | "ProposalReady"
      | "RoomInitialized"
      | "RoomResolved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "acceptedA", values?: undefined): string;
  encodeFunctionData(functionFragment: "acceptedB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "counterpartyEscrow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "counterpartyPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creatorPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decidedA", values?: undefined): string;
  encodeFunctionData(functionFragment: "decidedB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "finalSettlement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusLabel",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hasDeal", values?: undefined): string;
  encodeFunctionData(functionFragment: "partyA", values?: undefined): string;
  encodeFunctionData(functionFragment: "partyB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposedSettlement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "respondToProposal",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitCounterpartyPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submittedB",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "acceptedA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "acceptedB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "counterpartyEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "counterpartyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decidedA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decidedB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatusLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "partyA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "partyB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposedSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "respondToProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitCounterpartyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submittedB", data: BytesLike): Result;
}

export namespace CounterpartyPriceSubmittedEvent {
  export type InputTuple = [
    party: AddressLike,
    price: BigNumberish,
    escrowed: BigNumberish
  ];
  export type OutputTuple = [party: string, price: bigint, escrowed: bigint];
  export interface OutputObject {
    party: string;
    price: bigint;
    escrowed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecisionSubmittedEvent {
  export type InputTuple = [
    party: AddressLike,
    accepted: boolean,
    escrowed: BigNumberish
  ];
  export type OutputTuple = [
    party: string,
    accepted: boolean,
    escrowed: bigint
  ];
  export interface OutputObject {
    party: string;
    accepted: boolean;
    escrowed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalReadyEvent {
  export type InputTuple = [proposedSettlement: BigNumberish];
  export type OutputTuple = [proposedSettlement: bigint];
  export interface OutputObject {
    proposedSettlement: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomInitializedEvent {
  export type InputTuple = [
    partyA: AddressLike,
    partyB: AddressLike,
    creatorPrice: BigNumberish
  ];
  export type OutputTuple = [
    partyA: string,
    partyB: string,
    creatorPrice: bigint
  ];
  export interface OutputObject {
    partyA: string;
    partyB: string;
    creatorPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomResolvedEvent {
  export type InputTuple = [
    hasDeal: boolean,
    settlement: BigNumberish,
    refundToCounterparty: BigNumberish
  ];
  export type OutputTuple = [
    hasDeal: boolean,
    settlement: bigint,
    refundToCounterparty: bigint
  ];
  export interface OutputObject {
    hasDeal: boolean;
    settlement: bigint;
    refundToCounterparty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NegotiationRoom extends BaseContract {
  connect(runner?: ContractRunner | null): NegotiationRoom;
  waitForDeployment(): Promise<this>;

  interface: NegotiationRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptedA: TypedContractMethod<[], [boolean], "view">;

  acceptedB: TypedContractMethod<[], [boolean], "view">;

  counterpartyEscrow: TypedContractMethod<[], [bigint], "view">;

  counterpartyPrice: TypedContractMethod<[], [bigint], "view">;

  creatorPrice: TypedContractMethod<[], [bigint], "view">;

  decidedA: TypedContractMethod<[], [boolean], "view">;

  decidedB: TypedContractMethod<[], [boolean], "view">;

  finalSettlement: TypedContractMethod<[], [bigint], "view">;

  getStatusLabel: TypedContractMethod<[], [string], "view">;

  hasDeal: TypedContractMethod<[], [boolean], "view">;

  partyA: TypedContractMethod<[], [string], "view">;

  partyB: TypedContractMethod<[], [string], "view">;

  proposedSettlement: TypedContractMethod<[], [bigint], "view">;

  respondToProposal: TypedContractMethod<[accept: boolean], [void], "payable">;

  status: TypedContractMethod<[], [bigint], "view">;

  submitCounterpartyPrice: TypedContractMethod<
    [_counterpartyPrice: BigNumberish],
    [void],
    "payable"
  >;

  submittedB: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptedA"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "acceptedB"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "counterpartyEscrow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "counterpartyPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creatorPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decidedA"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "decidedB"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "finalSettlement"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatusLabel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasDeal"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "partyA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partyB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposedSettlement"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "respondToProposal"
  ): TypedContractMethod<[accept: boolean], [void], "payable">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitCounterpartyPrice"
  ): TypedContractMethod<[_counterpartyPrice: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "submittedB"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "CounterpartyPriceSubmitted"
  ): TypedContractEvent<
    CounterpartyPriceSubmittedEvent.InputTuple,
    CounterpartyPriceSubmittedEvent.OutputTuple,
    CounterpartyPriceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DecisionSubmitted"
  ): TypedContractEvent<
    DecisionSubmittedEvent.InputTuple,
    DecisionSubmittedEvent.OutputTuple,
    DecisionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalReady"
  ): TypedContractEvent<
    ProposalReadyEvent.InputTuple,
    ProposalReadyEvent.OutputTuple,
    ProposalReadyEvent.OutputObject
  >;
  getEvent(
    key: "RoomInitialized"
  ): TypedContractEvent<
    RoomInitializedEvent.InputTuple,
    RoomInitializedEvent.OutputTuple,
    RoomInitializedEvent.OutputObject
  >;
  getEvent(
    key: "RoomResolved"
  ): TypedContractEvent<
    RoomResolvedEvent.InputTuple,
    RoomResolvedEvent.OutputTuple,
    RoomResolvedEvent.OutputObject
  >;

  filters: {
    "CounterpartyPriceSubmitted(address,uint256,uint256)": TypedContractEvent<
      CounterpartyPriceSubmittedEvent.InputTuple,
      CounterpartyPriceSubmittedEvent.OutputTuple,
      CounterpartyPriceSubmittedEvent.OutputObject
    >;
    CounterpartyPriceSubmitted: TypedContractEvent<
      CounterpartyPriceSubmittedEvent.InputTuple,
      CounterpartyPriceSubmittedEvent.OutputTuple,
      CounterpartyPriceSubmittedEvent.OutputObject
    >;

    "DecisionSubmitted(address,bool,uint256)": TypedContractEvent<
      DecisionSubmittedEvent.InputTuple,
      DecisionSubmittedEvent.OutputTuple,
      DecisionSubmittedEvent.OutputObject
    >;
    DecisionSubmitted: TypedContractEvent<
      DecisionSubmittedEvent.InputTuple,
      DecisionSubmittedEvent.OutputTuple,
      DecisionSubmittedEvent.OutputObject
    >;

    "ProposalReady(uint256)": TypedContractEvent<
      ProposalReadyEvent.InputTuple,
      ProposalReadyEvent.OutputTuple,
      ProposalReadyEvent.OutputObject
    >;
    ProposalReady: TypedContractEvent<
      ProposalReadyEvent.InputTuple,
      ProposalReadyEvent.OutputTuple,
      ProposalReadyEvent.OutputObject
    >;

    "RoomInitialized(address,address,uint256)": TypedContractEvent<
      RoomInitializedEvent.InputTuple,
      RoomInitializedEvent.OutputTuple,
      RoomInitializedEvent.OutputObject
    >;
    RoomInitialized: TypedContractEvent<
      RoomInitializedEvent.InputTuple,
      RoomInitializedEvent.OutputTuple,
      RoomInitializedEvent.OutputObject
    >;

    "RoomResolved(bool,uint256,uint256)": TypedContractEvent<
      RoomResolvedEvent.InputTuple,
      RoomResolvedEvent.OutputTuple,
      RoomResolvedEvent.OutputObject
    >;
    RoomResolved: TypedContractEvent<
      RoomResolvedEvent.InputTuple,
      RoomResolvedEvent.OutputTuple,
      RoomResolvedEvent.OutputObject
    >;
  };
}
