/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NegotiationFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "allRooms" | "createRoom" | "roomCount" | "rooms"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RoomCreated"): EventFragment;

  encodeFunctionData(functionFragment: "allRooms", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createRoom",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "roomCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "rooms", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "allRooms", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createRoom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roomCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rooms", data: BytesLike): Result;
}

export namespace RoomCreatedEvent {
  export type InputTuple = [
    room: AddressLike,
    partyA: AddressLike,
    partyB: AddressLike,
    creatorPrice: BigNumberish
  ];
  export type OutputTuple = [
    room: string,
    partyA: string,
    partyB: string,
    creatorPrice: bigint
  ];
  export interface OutputObject {
    room: string;
    partyA: string;
    partyB: string;
    creatorPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NegotiationFactory extends BaseContract {
  connect(runner?: ContractRunner | null): NegotiationFactory;
  waitForDeployment(): Promise<this>;

  interface: NegotiationFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allRooms: TypedContractMethod<[], [string[]], "view">;

  createRoom: TypedContractMethod<
    [counterparty: AddressLike, creatorPrice: BigNumberish],
    [string],
    "nonpayable"
  >;

  roomCount: TypedContractMethod<[], [bigint], "view">;

  rooms: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allRooms"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "createRoom"
  ): TypedContractMethod<
    [counterparty: AddressLike, creatorPrice: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roomCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rooms"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "RoomCreated"
  ): TypedContractEvent<
    RoomCreatedEvent.InputTuple,
    RoomCreatedEvent.OutputTuple,
    RoomCreatedEvent.OutputObject
  >;

  filters: {
    "RoomCreated(address,address,address,uint256)": TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;
    RoomCreated: TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;
  };
}
